[package]
name = "pw2"
version = "0.1.0"
authors = ["Yarek Tyshchenko <yarekt@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.3.14"
shellexpand = "2.0.0"
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
